version: '3.8'

services:
  blazor-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blazor-chat-container
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./data:/app/data  # מיפוי תיקיית המידע לשמירת בסיס הנתונים
    networks:
      - blazor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  blazor-network:
    driver: bridge

volumes:
  blazor-data:
    driver: local