version: '3.8'
services:
  blazor-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    container_name: blazor-chat-container
    ports:
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # שינוי ל-Development לבדיקה
      - ASPNETCORE_URLS=http://+:80
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
    volumes:
      - ./data:/app/data  # מיפוי תיקיית המידע
      - ./logs:/app/logs  # הוספת מיפוי ללוגים
    networks:
      - blazor-network
    restart: unless-stopped
    # הסרת healthcheck זמנית לבדיקה
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s

networks:
  blazor-network:
    driver: bridge

volumes:
  blazor-data:
    driver: local
